apiVersion: v1
kind: Service
metadata:
  name: planguru-__PLANGURU_ENV__-api
  labels:
    app: planguru-__PLANGURU_ENV__-api
  name: planguru-__PLANGURU_ENV__-api
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: planguru-__PLANGURU_ENV__-api
  sessionAffinity: None
  type: ClusterIP

