apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planguru-__PLANGURU_ENV__-api
  name: planguru-__PLANGURU_ENV__-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: planguru-__PLANGURU_ENV__-api
  strategy:
    rollingUpdate:
      maxSurge: __MAX_SURGE__
      maxUnavailable: __MAX_UNAVAILABLE__
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: planguru-__PLANGURU_ENV__-api
    spec:
      containers:
        - env:
            - name: PLANGURU_ENV
              value: __PLANGURU_ENV__
          image: gcr.io/planguru-cloud/planguru-api-__PLANGURU_ENV__:__REVISION_ID__
          imagePullPolicy: Always
          name: planguru-cloud-sha256
          readinessProbe:
            failureThreshold: 1
            exec:
              command:
                - curl
                - http://localhost:3000/api/home
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 5
            exec:
              command:
                - curl
                - http://localhost:3000/api/home
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 15
          resources:
            limits:
              cpu: "3"
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      priorityClassName: __PLANGURU_ENV__-priority
      terminationGracePeriodSeconds: 15
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory