apiVersion: v1
kind: Service
metadata:
  name: scopeberry-__SCOPEBERRY_ENV__-frontend
  labels:
    app: scopeberry-__SCOPEBERRY_ENV__-frontend
  name: scopeberry-__SCOPEBERRY_ENV__-frontend
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: scopeberry-__SCOPEBERRY_ENV__-frontend
  sessionAffinity: None
  type: LoadBalancer
