apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planguru-__PLANGURU_ENV__-frontend
  name: planguru-__PLANGURU_ENV__-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: planguru-__PLANGURU_ENV__-frontend
  strategy:
    rollingUpdate:
      maxSurge: __MAX_SURGE__
      maxUnavailable: __MAX_UNAVAILABLE__
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: planguru-__PLANGURU_ENV__-frontend
    spec:
      containers:
        - image: gcr.io/planguru/planguru-frontend:__REVISION_ID__
          imagePullPolicy: Always
          name: planguru-cloud-sha256
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            failureThreshold: 3
            exec:
              command:
                - curl
                - http://localhost:80/
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 15

